version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  producer:
    build: .
    command: ["python", "producer.py"]
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      STOCK_SYMBOL: AAPL
    volumes:
      - ./logs:/app/logs
      - ./model:/app/model

  detector:
    build: .
    command: ["python", "anomalies_detector.py"]
    depends_on:
      - kafka
      - producer
    environment:
      KAFKA_BROKER: kafka:9092
    volumes:
      - ./logs:/app/logs
      - ./model:/app/model

  bot:
    build: .
    command: ["python", "bot_alerts.py"]
    depends_on:
      - kafka
      - detector
    environment:
      KAFKA_BROKER: kafka:9092
      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
    volumes:
      - ./logs:/app/logs

  dashboard:
    build: .
    command: ["streamlit", "run", "Dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
    depends_on:
      - kafka
      - detector
    environment:
      KAFKA_BROKER: kafka:9092
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./model:/app/model
